@host = http://localhost
@port = 5252
@Restaurants.API_HostAddress = http://localhost:5252
@token = CfDJ8Ip7Hfwesi9Gkoi7J0Rom6-6AheTGyI0S75Qcr2Q2rHlHF7FyCldzEQq1JFSwvJ9gBNA43e7kiUtMNNZEsqA20vaSa6Y7pfWFbpBlnbzqfHBe8ZVx-nlUMM2xjFxumHDtDnrjhWPyIn_doYZoxicjWk0m_V346pRxlr0kU65MLjkjBSJH3d--kRF-CE9bNPVfXiY0pX9EXa-aFc3vuOaPZgD9K_NuVeq1VBa_sZ2X-v0FW5ww_bKZZQ2LUEIQPqMDsdaMq7nNQGaqm0lQeS2sTDJ_oJRJ3v0DHI28yDgv0QumleIa1jH1AKhS9y9oVNi2_9VOfMI13DmUhenWkV6TlDU1YowgU7D8658rEKKxuFKRTw8NDyhikhdtX90ZqLp0x_5uLpGPEHCMcz74NwH6VpLWnYHPW5VVESEchzyoZ8GMhwN7bR9ty80BD0Mlwas8M_UT2xJi5IzMEH2vCA-XxQ4h-2z5BjfphX0XWnCnasdXrHNm9hFjzv3fLkoeKQXx0111HviEMCGxqGA3hdCEEPqUDPhksoH4LstGwxhhQYtqUGl_hscNUFstIqaAFYfxBybjut243BpTmS5MRA23lSB2NoEbQi49_DyR08LUaBMcsf7u8BlQB6LNNgYfN8c5m2CYfVfGg_OT-fTG8gFcQo97RPpl4Y459Gs7xZ4RzvlbO0puBX8p_jd8Sth8r7CJCHLwahIsZ5echJw3tgtDBi7c5aDgujIpNzRHmzwZ0jMjFwAtD4VzPuQC6m0DvWgHMf081HvGKJYkzopO6eKocrEVzCpjftLHYEzpdRIEI8IUunAfFLXi0CMvDpDfFVOYn7Ywz7xA3v7mwg2EuZC5cnoIxxiaeDuKQMRdOtTgyBju5SD9zNZ5OKTXTmdOXIO6w

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=a&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "Owner2 Restaurant2",
  "Description": "A new restaurant description",
  "Category": "rapida",
  "HasDelivery": true,
  "ContactEmail": "test@gmail.com",
  "ContactNumber": "123456789",
  "City": "New York",
  "Street": "123 Main St",
  "PostalCode": "10-001"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "Update Restaurant",
  "Description": "Test Update",
  "HasDelivery": false
}

###

@restaurantId=12
POST {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json

{
  "Name": "New Dishtest",
  "Description": "A new dish description",
  "Price": 9,
  "KiloCalories": 500
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes
Authorization: Bearer {{token}}

###

@dishId=6
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner2@gmail.com",
  "password": "Abc12345@"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
# "email": "test@gmail.com",
# "email": "admin@gmail.com",
# "email": "user@gmail.com",
# "email": "owner@gmail.com",
# "email": "owner2@gmail.com",
{
  "email": "owner@gmail.com",
  "password": "Abc12345@"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "owner2@gmail.com",
  "roleName": "Owner"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "Ecuadorian",
  "DateOfBirth": "2012-06-01"
}

###